services:
  web:
    build: .
    command: sh -c "sleep 30 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app  
    ports:
      - "8888:8000"  
    depends_on:
      - db  

  db:
    image: mysql:8.0 # obviously hide these in a .env or alike!
    restart: always
    environment:
      MYSQL_DATABASE: countriesdb
      MYSQL_USER: django_admin
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: rootpassword  # Set a root password
    #ports:
    #  - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql  

volumes:
  mysql_data: