name: Build test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Run Docker Compose in Detached Mode
      run: docker-compose up --build -d

    - name: Run Django makemigrations
      run: docker-compose exec -T web python3 manage.py makemigrations

    - name: Run Django migrate
      run: docker-compose exec -T web python3 manage.py migrate

    - name: Check MySQL Connection
      run: docker-compose exec -T db mysql -u django_admin -p'test123' -e "SHOW DATABASES;"

    - name: Wait for the Django server to be ready
      run: sleep 15 

    - name: Verify Django Admin is accessible
      run: curl --fail http://localhost:8888/admin || exit 1

    - name: Tear Down Docker Compose
      if: always()
      run: docker-compose down
